services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
    command: sh -c "if [ ${NODE_ENV} = 'development' ]; then npm run dev; else npm run start; fi"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
