name: Create Heroku Preview App

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-preview-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ github.head_ref }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: ${{ github.head_ref }}
          pipeline: shortner-url-portfolio
          app_exists: false

      - name: Add Comment to Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEROKU_APP_NAME: ${{ github.head_ref }}
        run: |
          APP_URL=$(heroku apps:info --app $HEROKU_APP_NAME | grep 'Web URL' | awk '{print $3}')
          COMMENT="Heroku Preview App is available at: $APP_URL"
          curl -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"body\": \"$COMMENT\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"

  destroy-preview-app:
    runs-on: ubuntu-latest
    needs: create-preview-app
    steps:
      - name: Wait for 30 minutes
        run: sleep 1800

      - name: Destroy Heroku Preview App
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_APP_NAME: ${{ github.head_ref }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          heroku apps:destroy --app $HEROKU_APP_NAME --confirm $HEROKU_APP_NAME
